import {
  RECEIPT_ONLINE_PAYMENT_BRANCH,
  RECEIPT_ONLINE_PAYMENT_CUSTOMER_NAME,
  RECEIPT_ONLINE_PAYMENT_MOBILE_NO,
  RECEIPT_ONLINE_PAYMENT_REF_NO,
  RECEIPT_ONLINE_PAYMENT_AMOUNT,
  RECEIPT_ONLINE_PAYMENT_NOTES,
  RECEIPT_ONLINE_PAYMENT_URL,
} from "../constants/receiptPayOnlineConstants";

export interface IReceiptPayOnlineForm {
  [RECEIPT_ONLINE_PAYMENT_BRANCH]: any;
  [RECEIPT_ONLINE_PAYMENT_CUSTOMER_NAME]: string;
  [RECEIPT_ONLINE_PAYMENT_MOBILE_NO]: string;
  [RECEIPT_ONLINE_PAYMENT_REF_NO]: string;
  [RECEIPT_ONLINE_PAYMENT_AMOUNT]: any;
  [RECEIPT_ONLINE_PAYMENT_NOTES]: string;
  [RECEIPT_ONLINE_PAYMENT_URL]: any;
}
